# Generated by Django 4.2.13 on 2024-07-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('point_one_title', models.CharField(max_length=100)),
                ('point_one_number', models.IntegerField()),
                ('point_two_title', models.CharField(max_length=100)),
                ('point_two_number', models.IntegerField()),
                ('point_three_title', models.CharField(max_length=100)),
                ('point_three_number', models.IntegerField()),
                ('button_text', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos')),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
        migrations.CreateModel(
            name='AboutUsPageBottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'About Us Page Bottom Banner',
                'verbose_name_plural': 'About Us Page Bottom Banner',
            },
        ),
        migrations.CreateModel(
            name='AboutUsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('values_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'About Us Story',
                'verbose_name_plural': 'About Us Story',
            },
        ),
        migrations.CreateModel(
            name='AboutUsStoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'About Us Story Value',
                'verbose_name_plural': 'About Us Story Values',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Details',
                'verbose_name_plural': 'Contact Details',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('download_catalog_title', models.CharField(max_length=100)),
                ('catalog_pdf_title', models.CharField(max_length=100)),
                ('catalog_pdf_link', models.CharField(max_length=100)),
                ('catalog_doc_title', models.CharField(max_length=100)),
                ('catalog_doc_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='ContactPageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('submit_button_text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Contact Page Form',
                'verbose_name_plural': 'Contact Page Form',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_banner_image', models.ImageField(upload_to='images')),
                ('top_banner_title', models.CharField(max_length=100)),
                ('top_banner_text', models.TextField()),
                ('top_banner_button_text', models.CharField(max_length=50)),
                ('section_one_title', models.CharField(max_length=100)),
                ('section_two_title', models.CharField(max_length=100)),
                ('section_two_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Home Page Detail',
                'verbose_name_plural': 'Home Page Detail',
            },
        ),
        migrations.CreateModel(
            name='HomePageBottomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_banner_title', models.CharField(max_length=100)),
                ('bottom_banner_text', models.TextField()),
                ('bottom_banner_button_text', models.CharField(max_length=50)),
                ('bottom_banner_point_one_number', models.IntegerField()),
                ('bottom_banner_point_one_text', models.CharField(max_length=100)),
                ('bottom_banner_point_two_number', models.IntegerField()),
                ('bottom_banner_point_two_text', models.CharField(max_length=100)),
                ('bottom_banner_point_three_number', models.IntegerField()),
                ('bottom_banner_point_three_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Home Page Bottom Banner',
                'verbose_name_plural': 'Home PageBottom Banner',
            },
        ),
        migrations.CreateModel(
            name='HomePageProvidingsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providing_image', models.ImageField(upload_to='images')),
                ('providing_title', models.CharField(max_length=100)),
                ('providing_text', models.TextField()),
                ('providing_button_text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Home Page Providings Item',
                'verbose_name_plural': 'Home Page Providings Items',
            },
        ),
        migrations.CreateModel(
            name='HomePageServicesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='images')),
                ('service_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Home Page Services Item',
                'verbose_name_plural': 'Home Page Services Items',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
