# Generated by Django 4.2.13 on 2024-07-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_providingsitempoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='point_one_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='point_three_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='point_two_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagebottombanner',
            name='bottom_banner_point_one_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagebottombanner',
            name='bottom_banner_point_three_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagebottombanner',
            name='bottom_banner_point_two_number',
            field=models.CharField(max_length=100),
        ),
    ]
