# Generated by Django 4.2.13 on 2024-07-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_image_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Product Page Details',
                'verbose_name_plural': 'Product Page Details',
            },
        ),
    ]
