# Generated by Django 4.2.13 on 2024-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productpagedetails_product_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpagedetails',
            name='related_products_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
