# Generated by Django 4.2.13 on 2024-07-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_contactpageform_submit_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpageform',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpageform',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpageform',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpageform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
